import { Container, Text } from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW={"7xl"}>
        <Text className="text-red-500" as={"h1"} fontSize={"2xl"}>
          NextJS Typescript + Chakra UI + Tailwind
        </Text>
      </Container>
    </div>
  );
};

export default Home;
