import {
  Container,
  Text,
  useColorMode,
  Button,
  Flex,
  Box,
} from "@chakra-ui/react";
import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  const { colorMode, toggleColorMode } = useColorMode();
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Container maxW={"7xl"} my={"6"}>
        <Flex justifyContent="flex-end">
          <Button onClick={toggleColorMode}>
            Toggle {colorMode === "light" ? "Dark" : "Light"}
          </Button>
        </Flex>
        <Box className="text-center">
          <Text className="text-red-500" as={"h1"} fontSize={"2xl"}>
            NextJS Typescript + Chakra UI + Tailwind
          </Text>
          <div className="dark:text-yellow-400">
            Tailwind is working, but Chakra UI is not working. I want to use
          </div>
        </Box>
      </Container>
    </div>
  );
};

export default Home;
